import { AppConfig } from '../types';

export function generateMainDart(config: AppConfig): string {
  const sanitizeName = config.appName.replace(/[^a-zA-Z0-9]/g, '');

  return `// =========================================================================
// Generated by Web2App by joo.exe - Flutter Multi-Platform Engine
// App Name: ${config.appName}
// Package: ${config.packageName}
// Version: ${config.version}
// Target URL: ${config.url}
// Date: ${new Date().toISOString()}
// =========================================================================

import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:url_launcher/url_launcher.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Set orientation and status bar overlay
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.light,
    ),
  );

  runApp(const Web2AppFlutterEngine());
}

class Web2AppFlutterEngine extends StatelessWidget {
  const Web2AppFlutterEngine({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '${config.appName}',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(${config.themeColor.replace('#', '0xFF')}),
          primary: const Color(${config.themeColor.replace('#', '0xFF')}),
          secondary: const Color(${config.accentColor.replace('#', '0xFF')}),
          background: const Color(${config.backgroundColor.replace('#', '0xFF')}),
        ),
      ),
      home: const AppSplashScreen(),
    );
  }
}

/// Splash Screen for ${config.appName}
class AppSplashScreen extends StatefulWidget {
  const AppSplashScreen({super.key});

  @override
  State<AppSplashScreen> createState() => _AppSplashScreenState();
}

class _AppSplashScreenState extends State<AppSplashScreen> {
  @override
  void initState() {
    super.initState();
    Timer(const Duration(seconds: ${config.splashDurationSec}), () {
      Navigator.of(context).pushReplacement(
        MaterialPageRoute(builder: (_) => const MainWebViewScreen()),
      );
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(${config.themeColor.replace('#', '0xFF')}),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            // App Icon
            Container(
              width: 100,
              height: 100,
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(24),
                boxShadow: const [
                  BoxShadow(
                    color: Colors.black26,
                    blurRadius: 20,
                    offset: Offset(0, 8),
                  )
                ],
              ),
              child: Center(
                child: Text(
                  '${config.iconEmoji}',
                  style: const TextStyle(fontSize: 50),
                ),
              ),
            ),
            const SizedBox(height: 24),
            Text(
              '${config.splashTitle}',
              style: const TextStyle(
                fontSize: 28,
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),
            const SizedBox(height: 8),
            Text(
              '${config.splashTagline}',
              style: TextStyle(
                fontSize: 14,
                color: Colors.white.withOpacity(0.85),
              ),
            ),
            const SizedBox(height: 40),
            const SpinKitThreeBounce(
              color: Colors.white,
              size: 28.0,
            ),
            const SizedBox(height: 12),
            Text(
              'Powered by Web2App joo.exe',
              style: TextStyle(
                fontSize: 10,
                color: Colors.white.withOpacity(0.6),
                letterSpacing: 1.2,
              ),
            )
          ],
        ),
      ),
    );
  }
}

/// Main WebView Screen
class MainWebViewScreen extends StatefulWidget {
  const MainWebViewScreen({super.key});

  @override
  State<MainWebViewScreen> createState() => _MainWebViewScreenState();
}

class _MainWebViewScreenState extends State<MainWebViewScreen> {
  late final WebViewController _controller;
  bool _isLoading = true;
  double _loadingProgress = 0.0;
  bool _isOffline = false;
  late StreamSubscription<ConnectivityResult> _connectivitySubscription;

  final String _initialUrl = '${config.url}';

  @override
  void initState() {
    super.initState();
    _initWebView();
    _checkConnectivity();
  }

  void _initWebView() {
    final WebViewController controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(const Color(${config.backgroundColor.replace('#', '0xFF')}))
      ..setNavigationDelegate(
        NavigationDelegate(
          onProgress: (int progress) {
            setState(() {
              _loadingProgress = progress / 100;
            });
          },
          onPageStarted: (String url) {
            setState(() {
              _isLoading = true;
            });
          },
          onPageFinished: (String url) {
            setState(() {
              _isLoading = false;
            });
${config.enableCustomCssJs && config.customCss ? `            // Inject Custom CSS
            _controller.runJavaScript('''
              (function() {
                var style = document.createElement('style');
                style.type = 'text/css';
                style.innerHTML = \`${config.customCss.replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`;
                document.head.appendChild(style);
              })();
            ''');` : ''}
${config.enableCustomCssJs && config.customJs ? `            // Inject Custom JavaScript
            _controller.runJavaScript('''
              ${config.customJs.replace(/`/g, '\\`').replace(/\$/g, '\\$')}
            ''');` : ''}
          },
          onWebResourceError: (WebResourceError error) {
            if (error.errorType == WebResourceErrorType.hostLookup ||
                error.errorType == WebResourceErrorType.connect) {
              setState(() {
                _isOffline = true;
              });
            }
          },
          onNavigationRequest: (NavigationRequest request) {
            if (!request.url.startsWith('http')) {
              _launchExternalUrl(request.url);
              return NavigationDecision.prevent;
            }
            return NavigationDecision.navigate;
          },
        ),
      );

${config.enableCustomUserAgent && config.customUserAgent ? `    controller.setUserAgent("${config.customUserAgent}");` : ''}

    controller.loadRequest(Uri.parse(_initialUrl));
    _controller = controller;
  }

  void _checkConnectivity() {
    _connectivitySubscription = Connectivity().onConnectivityChanged.listen((ConnectivityResult result) {
      if (result == ConnectivityResult.none) {
        setState(() {
          _isOffline = true;
        });
      } else if (_isOffline) {
        setState(() {
          _isOffline = false;
        });
        _controller.reload();
      }
    });
  }

  Future<void> _launchExternalUrl(String url) async {
    final Uri uri = Uri.parse(url);
    if (await canLaunchUrl(uri)) {
      await launchUrl(uri, mode: LaunchMode.externalApplication);
    }
  }

  @override
  void dispose() {
    _connectivitySubscription.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async {
        if (await _controller.canGoBack()) {
          _controller.goBack();
          return false;
        }
        return true;
      },
      child: Scaffold(
${config.navMode === 'header' ? `        appBar: AppBar(
          backgroundColor: const Color(${config.themeColor.replace('#', '0xFF')}),
          foregroundColor: Colors.white,
          title: Text('${config.appName}'),
          actions: [
            IconButton(
              icon: const Icon(Icons.refresh),
              onPressed: () => _controller.reload(),
            ),
            IconButton(
              icon: const Icon(Icons.arrow_back_ios_new, size: 20),
              onPressed: () async {
                if (await _controller.canGoBack()) {
                  _controller.goBack();
                }
              },
            ),
            IconButton(
              icon: const Icon(Icons.arrow_forward_ios, size: 20),
              onPressed: () async {
                if (await _controller.canGoForward()) {
                  _controller.goForward();
                }
              },
            ),
          ],
        ),` : ''}
        body: SafeArea(
          child: Stack(
            children: [
              if (!_isOffline)
${config.enablePullToRefresh ? `                RefreshIndicator(
                  color: const Color(${config.themeColor.replace('#', '0xFF')}),
                  onRefresh: () async {
                    await _controller.reload();
                  },
                  child: WebViewWidget(controller: _controller),
                )` : `                WebViewWidget(controller: _controller)`},

              if (_isLoading && !_isOffline)
                Positioned(
                  top: 0,
                  left: 0,
                  right: 0,
                  child: LinearProgressIndicator(
                    value: _loadingProgress,
                    backgroundColor: Colors.transparent,
                    valueColor: AlwaysStoppedAnimation<Color>(
                      const Color(${config.accentColor.replace('#', '0xFF')}),
                    ),
                  ),
                ),

              if (_isOffline)
                _buildOfflineView(),
            ],
          ),
        ),
${config.enableFloatingButton ? `        floatingActionButtonLocation: ${config.fabPosition === 'bottom_left' ? 'FloatingActionButtonLocation.startFloat' : 'FloatingActionButtonLocation.endFloat'},
        floatingActionButton: FloatingActionButton.extended(
          backgroundColor: const Color(0xFF25D366),
          elevation: 6,
          onPressed: () {
            ${config.fabType === 'whatsapp' ? `_launchExternalUrl('https://wa.me/${config.fabTarget || '6281234567890'}');` : config.fabType === 'call' ? `_launchExternalUrl('tel:${config.fabTarget || '6281234567890'}');` : config.fabType === 'custom_js' ? `_controller.runJavaScript('${config.fabTarget || 'alert("FAB Clicked!");'}');` : `_launchExternalUrl('${config.fabTarget || 'https://google.com'}');`}
          },
          icon: const Icon(Icons.chat_bubble_rounded, color: Colors.white),
          label: const Text('Live Chat', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
        ),` : ''}
      ),
    );
  }

  Widget _buildOfflineView() {
    return Container(
      color: Colors.white,
      padding: const EdgeInsets.all(24),
      child: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(
              Icons.wifi_off_rounded,
              size: 80,
              color: Colors.grey,
            ),
            const SizedBox(height: 20),
            const Text(
              'No Internet Connection',
              style: TextStyle(
                fontSize: 22,
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 10),
            const Text(
              'Please check your network settings and tap retry below to reload ${config.appName}.',
              textAlign: TextAlign.center,
              style: TextStyle(color: Colors.black54),
            ),
            const SizedBox(height: 30),
            ElevatedButton.icon(
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(${config.themeColor.replace('#', '0xFF')}),
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(horizontal: 28, vertical: 14),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
              ),
              onPressed: () {
                setState(() {
                  _isOffline = false;
                  _isLoading = true;
                });
                _controller.reload();
              },
              icon: const Icon(Icons.refresh),
              label: const Text('Try Again'),
            ),
          ],
        ),
      ),
    );
  }
}
`;
}

export function generatePubspecYaml(config: AppConfig): string {
  return `name: ${config.appName.toLowerCase().replace(/[^a-z0-9_]/g, '_')}
description: "${config.splashTagline || 'Converted Web2App Flutter multi-platform application'}"
publish_to: 'none'
version: ${config.version}

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.10.0
  connectivity_plus: ^6.1.0
  flutter_spinkit: ^5.2.1
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
`;
}

export function generateAndroidManifest(config: AppConfig): string {
  return `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="${config.packageName}">

    <!-- Network Permissions -->
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>

${config.permissions.camera ? '    <uses-permission android:name="android.permission.CAMERA"/>\n' : ''}${config.permissions.location ? '    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>\n    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>\n' : ''}${config.permissions.storage ? '    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>\n    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>\n' : ''}${config.permissions.microphone ? '    <uses-permission android:name="android.permission.RECORD_AUDIO"/>\n' : ''}${config.permissions.notifications ? '    <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>\n' : ''}${config.enableBiometrics ? '    <uses-permission android:name="android.permission.USE_BIOMETRIC"/>\n' : ''}
    <application
        android:label="${config.appName}"
        android:name="\${applicationName}"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
`;
}

export function generateInfoPlist(config: AppConfig): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>${config.appName}</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>${config.packageName}</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>${config.appName}</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>${config.version}</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
${config.permissions.camera ? '	<key>NSCameraUsageDescription</key>\n	<string>This app requires camera access for photo uploads.</string>\n' : ''}${config.permissions.location ? '	<key>NSLocationWhenInUseUsageDescription</key>\n	<string>This app requires location access for localized features.</string>\n' : ''}${config.permissions.microphone ? '	<key>NSMicrophoneUsageDescription</key>\n	<string>This app requires microphone access for voice input.</string>\n' : ''}	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
</dict>
</plist>
`;
}

export function generatePwaManifest(config: AppConfig): string {
  return JSON.stringify(
    {
      name: config.appName,
      short_name: config.appName,
      start_url: config.url,
      display: "standalone",
      background_color: config.backgroundColor,
      theme_color: config.themeColor,
      description: config.splashTagline,
      icons: [
        {
          src: "icons/Icon-192.png",
          sizes: "192x192",
          type: "image/png",
        },
        {
          src: "icons/Icon-512.png",
          sizes: "512x512",
          type: "image/png",
        },
      ],
    },
    null,
    2
  );
}

export function generateReadme(config: AppConfig): string {
  return `# ${config.appName} - Flutter App

Generated by **Web2App by joo.exe**
Target URL: \`${config.url}\`
Package Name: \`${config.packageName}\`

## Quick Start Guide

### Prerequisites
1. Install [Flutter SDK 3.x or later](https://docs.flutter.dev/get-started/install)
2. Install Android Studio (for Android builds) or Xcode (for iOS builds)

### How to Run the App
\`\`\`bash
# 1. Extract this zip folder
cd ${config.appName.toLowerCase().replace(/[^a-z0-9_]/g, '_')}

# 2. Fetch Flutter dependencies
flutter pub get

# 3. Launch on emulator or connected device
flutter run
\`\`\`

### How to Build Release APK / App Bundle
\`\`\`bash
# Build Android APK (Output in build/app/outputs/flutter-apk/app-release.apk)
flutter build apk --release

# Build Android App Bundle for Google Play
flutter build appbundle --release

# Build iOS Release
flutter build ios --release

# Build Flutter Web App
flutter build web --release
\`\`\`

## Features Included
- **Multi-Platform Support**: Android, iOS, Web, Windows, macOS
- **High-Performance WebView Engine**: Smooth scrolling and full JavaScript execution
- **Smart Connectivity Guard**: Live online/offline detection with custom retry screen
- **Pull to Refresh**: ${config.enablePullToRefresh ? 'Enabled' : 'Disabled'}
- **Android Hardware Back Button Handler**: Native back stack navigation
- **Custom Splash Screen**: Styled with brand colors and animated loader
`;
}

export function generateGithubWorkflow(config: AppConfig): string {
  const sanitizeName = (config.appName || 'app').toLowerCase().replace(/[^a-z0-9_]/g, '_') || 'app';
  return `name: Auto Build Flutter APK & Release

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${sanitizeName}-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
`;
}

